import { body, checkExact } from "express-validator";

export const adminRegister = checkExact([
  body('name')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Name is required')
    .isString()
    .bail()
    .withMessage('Name must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('Name must have some value'),
  body('email')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Email is required')
    .isString()
    .bail()
    .withMessage('Email must be a string')
    .isEmail()
    .bail()
    .withMessage('Email must be valid'),
  body('password')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Password is required')
    .isString()
    .bail()
    .withMessage('Password must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('Password must have some value'),
])

export const adminLogin = checkExact([
    body('email')
      .exists({ values: "falsy" })
      .bail()
      .withMessage('Email is required')
      .isString()
      .bail()
      .withMessage('Email must be a string')
      .isEmail()
      .bail()
      .withMessage('Email must be valid'),
    body('password')
      .exists({ values: "falsy" })
      .bail()
      .withMessage('Password is required')
      .isString()
      .bail()
      .withMessage('Password must be a string')
      .trim()
      .notEmpty()
      .bail()
      .withMessage('Password must have some value'),
])

export const adminUpdate = checkExact([
  body('name')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Name is required')
    .isString()
    .bail()
    .withMessage('Name must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('Name must have some value'),
  body('profileImage')
    .optional()
    .isString()
    .bail()
    .withMessage('Profile image must be a string'),
])

export const adminChangePassword = checkExact([
  body('oldPassword')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Old password is required')
    .isString()
    .bail()
    .withMessage('Old password must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('Old password must have some value'),
  body('newPassword')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('New password is required')
    .isString()
    .bail()
    .withMessage('New password must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('New password must have some value'),
])

export const adminForgotPassword = checkExact([
  body('email')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Email is required')
    .isString()
    .bail()
    .withMessage('Email must be a string')
    .isEmail()
    .bail()
    .withMessage('Email must be valid'),
])

export const adminResetPassword = checkExact([
  body('email')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Email is required')
    .isString()
    .bail()
    .withMessage('Email must be a string')
    .isEmail()
    .bail()
    .withMessage('Email must be valid'),
  body('password')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Password is required')
    .isString()
    .bail()
    .withMessage('Password must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('Password must have some value'),
  body('otp')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Otp is required')
    .isString()
    .bail()
    .withMessage('Otp must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('Otp must have some value'),
])

export const adminVerifyOtp = checkExact([
  body('email')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Email is required')
    .isString()
    .bail()
    .withMessage('Email must be a string')
    .isEmail()
    .bail()
    .withMessage('Email must be valid'),
  body('otp')
    .exists({ values: "falsy" })
    .bail()
    .withMessage('Otp is required')
    .isString()
    .bail()
    .withMessage('Otp must be a string')
    .trim()
    .notEmpty()
    .bail()
    .withMessage('Otp must have some value'),
])